ok

diff --git a/analysis-by-project/script/distribute_Analysis b/analysis-by-project/script/distribute_Analysis
--- a/analysis-by-project/script/distribute_Analysis
+++ b/analysis-by-project/script/distribute_Analysis
@@ -1,21 +1,17 @@
 #!/bin/bash
+set -eu -o pipefail
+trap 'echo "ERROR: line no = $LINENO, exit status = $?" >&2; exit 1' ERR
 
+readonly DIR_SCRIPT="$(cd $(dirname ${0}); pwd)"
+readonly DIR_LIB="${DIR_SCRIPT}/lib"
 
-readonly DIR_NON_TRIAL="$(cd "$(dirname $0)/../../.."&&pwd)"
-readonly DIR_ANALYSIS_SERVICE="$(cd "$(dirname $0)/../.."&&pwd)"
-readonly DIR_ANALYSIS_BY_PROJECT="$(cd "$(dirname $0)/.."&&pwd)"
-
-readonly DIR_PACKAGE="${DIR_ANALYSIS_BY_PROJECT:?}/package"
-readonly DIR_TASK="${DIR_ANALYSIS_BY_PROJECT:?}/task"
-readonly FILE_ALL_TASK="${DIR_TASK:?}/task_all.tsv"
-
+. "${DIR_LIB}/common.sh"
 
 
 echo "##### 解析用Fortranのコンパイル" && {
 "${DIR_PACKAGE:?}/cmake_build.sh"
 "${DIR_PACKAGE:?}/make_dist.sh"
 }
-
 
 echo "##### 解析スクリプトの配布 #####"
 while read dir_analysis fst_run lst_run
